name: "deploy to dev"

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]

env:
  IMAGE_NAME: noodleflix

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev

    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'

      - name: Sets variables
        id: variables
        run: |
          IMAGE_REGISTRY="docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}"
          IMAGE_TAG=dev-${{ github.run_number }}
          
          echo "IMAGE_REGISTRY=$IMAGE_REGISTRY" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Print variables
        run: |
          echo "IMAGE_REGISTRY=$IMAGE_REGISTRY"
          echo "IMAGE_TAG=$IMAGE_TAG"
      - name: Log in Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image
        run: mvn clean package -DskipTests spring-boot:build-image --no-transfer-progress -Dspring-boot.build-image.imageName=$IMAGE_REGISTRY:$IMAGE_TAG
      - name: Push image
        run: docker push $IMAGE_REGISTRY:$IMAGE_TAG